version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: tourism_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mytourappdb
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: tourism_app
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mytourappdb
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn install && yarn dev"

volumes:
  dbdata: